import Foundation

/// Native implementation of HybridNitroTorchProtocol.
/// This file is yours to edit — the protocol is generated by `nitrogen generate`.
public class NitroTorchImpl: NSObject, HybridNitroTorchProtocol {

    public func add(a: Double, b: Double) -> Double {
        return a + b
    }

    public func getGreeting(name: String) async throws -> String {
        return "Hello, \(name)!"
    }
}
