package dev.shreeman.nitro_torch

import android.content.Context
import nitro.nitro_torch_module.HybridNitroTorchSpec

/// Native implementation of HybridNitroTorchSpec.
/// This file is yours to edit — the interface is generated by `nitrogen generate`.
class NitroTorchImpl(private val context: Context) : HybridNitroTorchSpec {

    override fun add(a: Double, b: Double): Double = a + b

    override suspend fun getGreeting(name: String): String = "Hello, $name!"
}
