// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.5
// Generated from: nitro_torch.native.dart
// ignore_for_file: no_leading_underscores_for_local_identifiers, prefer_typing_uninitialized_variables
part of 'nitro_torch.native.dart';

// --- Enum FFI helpers (generated by Nitrogen) ---

extension TorchStateNativeExt on TorchState {
  int get nativeValue => index + 0;
}

extension TorchStateFromNativeExt on int {
  TorchState toTorchState() => TorchState.values[this - 0];
}

// --- Struct FFI representations (generated by Nitrogen) ---

final class TorchLevelFfi extends Struct {
  @Int64()
  external int level;
  @Int64()
  external int maxLevel;
}

extension TorchLevelFfiExt on TorchLevelFfi {
  TorchLevel toDart() {
    return TorchLevel(level: level, maxLevel: maxLevel);
  }

  /// Frees internal fields (like strings) that were allocated on the C heap.
  /// Does NOT free the struct itself.
  void freeFields() {}
}

extension TorchLevelExt on TorchLevel {
  Pointer<TorchLevelFfi> toNative(Arena arena) {
    final ptr = arena<TorchLevelFfi>();
    ptr.ref.level = level;
    ptr.ref.maxLevel = maxLevel;
    return ptr;
  }
}

// --- Struct Native Proxies (zero-copy, lazy field access) ---

/// Zero-copy proxy for [TorchLevel].
/// Extends [TorchLevel] and overrides every getter to read lazily from
/// native memory — no field is copied at construction time.
/// Because `TorchLevelProxy <: TorchLevel`, a `Stream<TorchLevelProxy>`
/// satisfies `Stream<TorchLevel>` via Dart covariant generics.
/// Native memory is freed via a [NativeFinalizer] backed by the
/// generated C symbol 'nitro_torch_release_TorchLevel'.
/// Ownership: this proxy owns the generated struct shell. Zero-copy
/// field buffers remain owned by the native implementation and must
/// stay valid until this proxy is released by the finalizer or
/// [toDartAndRelease].
final class TorchLevelProxy extends TorchLevel implements Finalizable {
  final Pointer<TorchLevelFfi> _native;

  static NativeFinalizer? _finalizer;

  /// Binds the generated release symbol from [dylib].
  /// Must be called once — typically in the impl class constructor.
  /// Idempotent: subsequent calls are a no-op.
  static void _init(DynamicLibrary dylib) {
    _finalizer ??= NativeFinalizer(
      dylib.lookup<NativeFunction<Void Function(Pointer<Void>)>>(
        'nitro_torch_release_TorchLevel',
      ),
    );
  }

  /// Takes ownership of [native]. Super fields are zeroed and never read;
  /// all getters below are overridden to read from native memory instead.
  /// Do NOT call [malloc.free] on the struct shell after passing it here,
  /// and do not free zero-copy field buffers while the proxy may be read.
  TorchLevelProxy(this._native) : super(level: 0, maxLevel: 0) {
    assert(
      _finalizer != null,
      'TorchLevelProxy._init() was not called. Ensure the Nitro impl class constructor ran before creating proxies.',
    );
    _finalizer!.attach(this, _native.cast(), detach: this);
  }

  // @override lazy getters — read native memory on demand, zero allocation.
  @override
  int get level => _native.ref.level;
  @override
  int get maxLevel => _native.ref.maxLevel;

  /// Eagerly copies all fields to a plain [TorchLevel] value, detaches
  /// the finalizer, and frees native memory immediately.
  /// Use this only when you need an immutable snapshot; for streams
  /// prefer consuming the proxy fields lazily then letting it GC.
  /// Must not be called more than once.
  TorchLevel toDartAndRelease() {
    final v = _native.ref.toDart();
    _finalizer?.detach(this);
    malloc.free(_native);
    return v;
  }
}

class _NitroTorchImpl extends NitroTorch {
  final DynamicLibrary _dylib;
  final Pointer<NitroErrorFfi> _nitroErr = calloc<NitroErrorFfi>();
  final Map<Object, NativeCallable<dynamic>> _nativeCallbackCache = {};

  static DynamicLibrary _loadSupportedLibrary() {
    return NitroRuntime.loadLibForTargets(
      'nitro_torch',
      ios: true,
      android: true,
      macos: true,
      windows: true,
      linux: true,
      web: false,
    );
  }

  _NitroTorchImpl() : _dylib = _loadSupportedLibrary() {
    final initSw = Stopwatch()..start();
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_torch_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_torch: Dart API DL initialization failed with code $initCode.',
      );
    }
    NitroRuntime.checkAbiVersion(
      'nitro_torch',
      () => _dylib.lookupFunction<Uint32 Function(), int Function()>(
        'nitro_torch_nitro_abi_version',
      )(),
    );
    NitroRuntime.checkLinkChecksum(
      'nitro_torch',
      '7550b46964153fd1',
      () => _dylib
          .lookupFunction<Pointer<Utf8> Function(), Pointer<Utf8> Function()>(
            'nitro_torch_nitro_bridge_checksum',
          )()
          .toDartString(),
    );
    TorchLevelProxy._init(_dylib);
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_torch)',
      'initialized in ${initSw.elapsedMicroseconds} µs',
    );
  }

  late final void Function(
    Pointer<NativeFunction<Void Function(Int64)>>,
    Pointer<NitroErrorFfi>,
  )
  _onCallbackPtr = _dylib
      .lookupFunction<
        Void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        ),
        void Function(
          Pointer<NativeFunction<Void Function(Int64)>>,
          Pointer<NitroErrorFfi>,
        )
      >('nitro_torch_on_callback');
  late final void Function(Pointer<NitroErrorFfi>) _turnOnPtr = _dylib
      .lookup<NativeFunction<Void Function(Pointer<NitroErrorFfi>)>>(
        'nitro_torch_turn_on',
      )
      .asFunction<void Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(Pointer<NitroErrorFfi>) _turnOffPtr = _dylib
      .lookup<NativeFunction<Void Function(Pointer<NitroErrorFfi>)>>(
        'nitro_torch_turn_off',
      )
      .asFunction<void Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final int Function(Pointer<NitroErrorFfi>) _getStatusPtr = _dylib
      .lookup<NativeFunction<Int8 Function(Pointer<NitroErrorFfi>)>>(
        'nitro_torch_get_status',
      )
      .asFunction<int Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(Pointer<NitroErrorFfi>) _togglePtr = _dylib
      .lookup<NativeFunction<Void Function(Pointer<NitroErrorFfi>)>>(
        'nitro_torch_toggle',
      )
      .asFunction<void Function(Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final void Function(int, Pointer<NitroErrorFfi>) _setLevelPtr = _dylib
      .lookup<NativeFunction<Void Function(Int64, Pointer<NitroErrorFfi>)>>(
        'nitro_torch_set_level',
      )
      .asFunction<void Function(int, Pointer<NitroErrorFfi>)>(isLeaf: true);
  late final Pointer<Uint8> Function(Pointer<NitroErrorFfi>) _maxLevelPtr =
      _dylib.lookupFunction<
        Pointer<Uint8> Function(Pointer<NitroErrorFfi>),
        Pointer<Uint8> Function(Pointer<NitroErrorFfi>)
      >('nitro_torch_max_level');
  late final void Function(int) _registerOnLevelChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_torch_register_on_level_changed_stream',
      );
  late final void Function(int) _releaseOnLevelChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_torch_release_on_level_changed_stream',
      );
  late final void Function(int) _registerOnTorchStateChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_torch_register_on_torch_state_changed_stream',
      );
  late final void Function(int) _releaseOnTorchStateChangedPtr = _dylib
      .lookupFunction<Void Function(Int64), void Function(int)>(
        'nitro_torch_release_on_torch_state_changed_stream',
      );
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_torch_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_torch_clear_error',
      );

  @override
  void dispose() {
    NitroRuntime.logLifecycle('dispose(nitro_torch)', 'disposing');
    for (final callback in _nativeCallbackCache.values) {
      callback.close();
    }
    _nativeCallbackCache.clear();
    calloc.free(_nitroErr); // S8: free pre-allocated error slot
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_torch)', 'disposed');
  }

  // Native callback handles are cached so native code can retain
  // callback pointers safely until this HybridObject is disposed.
  NativeCallable<Void Function(Int64)> _nativeCallbackOnCallbackCallback(
    void Function(TorchState) callback,
  ) {
    final key = ('onCallback.callback', callback);
    return _nativeCallbackCache.putIfAbsent(key, () {
          return NativeCallable<Void Function(Int64)>.listener((int arg0) {
            callback(arg0.toTorchState());
          });
        })
        as NativeCallable<Void Function(Int64)>;
  }

  @override
  void onCallback(void Function(TorchState) callback) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _onCallbackPtr(
        _nativeCallbackOnCallbackCallback(callback).nativeFunction,
        _nitroErr,
      );
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'onCallback');
  }

  @override
  void turnOn() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _turnOnPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'turnOn');
  }

  @override
  void turnOff() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _turnOffPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'turnOff');
  }

  @override
  bool getStatus() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _getStatusPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return res != 0;
    }, methodName: 'getStatus');
  }

  @override
  void toggle() {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _togglePtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'toggle');
  }

  @override
  void setLevel(int level) {
    checkDisposed();
    NitroRuntime.callSync<void>(() {
      _setLevelPtr(level, _nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
    }, methodName: 'setLevel');
  }

  @override
  int? maxLevel() {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _maxLevelPtr(_nitroErr);
      NitroRuntime.throwIfOutParamError(_nitroErr);
      return NitroNullableInt.fromNative(res).nullable;
    }, methodName: 'maxLevel');
  }

  @override
  Stream<TorchLevel> onLevelChanged() {
    checkDisposed();
    return NitroRuntime.openStream<TorchLevelProxy>(
      register: (port) => _registerOnLevelChangedPtr(port),
      unpack: (message) {
        if (message == null) {
          throw StateError(
            'Received null event on non-nullable stream onLevelChanged',
          );
        }
        return TorchLevelProxy(
          Pointer<TorchLevelFfi>.fromAddress(message as int),
        );
      },
      release: (port) => _releaseOnLevelChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }

  @override
  Stream<TorchState> onTorchStateChanged() {
    checkDisposed();
    return NitroRuntime.openStream<TorchState>(
      register: (port) => _registerOnTorchStateChangedPtr(port),
      unpack: (message) => (message as int).toTorchState(),
      release: (port) => _releaseOnTorchStateChangedPtr(port),
      backpressure: Backpressure.dropLatest,
    );
  }
}
