// Generated by Nitrogen Modules. Do not edit.
// Generated from: nitro_torch.native.dart
part of 'nitro_torch.native.dart';

class _NitroTorchImpl extends NitroTorch {
  final DynamicLibrary _dylib;

  _NitroTorchImpl() : _dylib = NitroRuntime.loadLib('nitro_torch') {
    final initSw = Stopwatch()..start();
    final initFunc = _dylib
        .lookupFunction<
          IntPtr Function(Pointer<Void>),
          int Function(Pointer<Void>)
        >('nitro_torch_init_dart_api_dl');
    final initCode = initFunc(NativeApi.initializeApiDLData);
    if (initCode != 0) {
      throw StateError(
        'nitro_torch: Dart API DL initialization failed with code $initCode.',
      );
    }
    initSw.stop();
    NitroRuntime.logLifecycle(
      'init(nitro_torch)',
      'initialized in ${initSw.elapsedMicroseconds} µs',
    );
  }

  late final double Function(double, double) _addPtr = _dylib
      .lookup<NativeFunction<Double Function(Double, Double)>>(
        'nitro_torch_add',
      )
      .asFunction<double Function(double, double)>(isLeaf: true);
  late final Pointer<Utf8> Function(Pointer<Utf8>) _getGreetingPtr = _dylib
      .lookupFunction<
        Pointer<Utf8> Function(Pointer<Utf8>),
        Pointer<Utf8> Function(Pointer<Utf8>)
      >('nitro_torch_get_greeting');
  // ignore: unused_field
  late final Pointer<NitroErrorFfi> Function() _getErrorPtr = _dylib
      .lookupFunction<
        Pointer<NitroErrorFfi> Function(),
        Pointer<NitroErrorFfi> Function()
      >('nitro_torch_get_error');
  // ignore: unused_field
  late final void Function() _clearErrorPtr = _dylib
      .lookupFunction<Void Function(), void Function()>(
        'nitro_torch_clear_error',
      );
  // ignore: unused_field
  late final Pointer<NativeFunction<Pointer<NitroErrorFfi> Function()>>
  _getErrorNativePtr = _dylib.lookup('nitro_torch_get_error');
  // ignore: unused_field
  late final Pointer<NativeFunction<Void Function()>> _clearErrorNativePtr =
      _dylib.lookup('nitro_torch_clear_error');

  @override
  void dispose() {
    NitroRuntime.logLifecycle('dispose(nitro_torch)', 'disposing');
    super.dispose(); // sets isDisposed = true, calls onDestroy()
    NitroRuntime.logLifecycle('dispose(nitro_torch)', 'disposed');
  }

  @override
  double add(double a, double b) {
    checkDisposed();
    return NitroRuntime.callSync(() {
      final res = _addPtr(a, b);
      NitroRuntime.checkError(_getErrorPtr, _clearErrorPtr);
      return res;
    }, methodName: 'add');
  }

  @override
  Future<String> getGreeting(String name) async {
    checkDisposed();
    final arena = Arena();
    try {
      final rawPtr = await NitroRuntime.callAsync<Pointer<Utf8>>(
        _getGreetingPtr,
        [name.toNativeUtf8(allocator: arena)],
        getError: _getErrorNativePtr,
        clearError: _clearErrorNativePtr,
        methodName: 'getGreeting',
      );
      return rawPtr.toDartStringWithFree();
    } finally {
      arena.releaseAll();
    }
  }
}
