// HybridNitroTorch — WindowsNativeImpl.cpp implementation.
// Generated by nitrogen link. Fill in the method bodies.
#include "../../lib/src/generated/cpp/nitro_torch.native.g.h"

#include <string>

class HybridNitroTorchImpl final : public HybridNitroTorch {
public:
    // TODO: implement all pure-virtual methods declared in HybridNitroTorch
};

// MSVC static-initializer auto-registration (no __attribute__((constructor)) on Windows).
namespace {
  struct _AutoRegister {
    _AutoRegister() { nitro_torch_register_impl(new HybridNitroTorchImpl()); }
  };
  static _AutoRegister _auto_register_instance;
}
