// Generated by Nitrogen Modules. Do not edit.
// nitro_generator: 0.4.4
// Generated from: nitro_torch.native.dart
import Foundation
import Combine

// --- Enums ---
public enum TorchState: Int64 {
  case on = 0
  case off = 1
}

// --- Structs ---
public struct TorchLevel {
  public var level: Int64
  public var maxLevel: Int64
}

// C-ABI shadow — layout matches the C typedef TorchLevel
fileprivate struct _TorchLevelC {
  var level: Int64
  var maxLevel: Int64

  static func fromSwift(_ s: TorchLevel) -> _TorchLevelC {
    return _TorchLevelC(
      level: s.level,
      maxLevel: s.maxLevel
    )
  }

  func toSwift() -> TorchLevel {
    return TorchLevel(
      level: level,
      maxLevel: maxLevel
    )
  }
}

// --- @HybridRecord binary extensions (generated by Nitrogen) ---

public struct NitroNullableInt {
  public var hasValue: Bool
  public var value: Int64

  public init(hasValue: Bool, value: Int64) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableInt {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableInt {
    return NitroNullableInt(
      hasValue: r.readBool(),
      value: r.readInt(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeInt(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableDouble {
  public var hasValue: Bool
  public var value: Double

  public init(hasValue: Bool, value: Double) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableDouble {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableDouble {
    return NitroNullableDouble(
      hasValue: r.readBool(),
      value: r.readDouble(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeDouble(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public struct NitroNullableBool {
  public var hasValue: Bool
  public var value: Bool

  public init(hasValue: Bool, value: Bool) {
    self.hasValue = hasValue
    self.value = value
  }

  public static func fromNative(_ ptr: UnsafeMutablePointer<UInt8>) -> NitroNullableBool {
    return fromReader(NitroRecordReader(ptr: ptr))
  }

  public static func fromReader(_ r: NitroRecordReader) -> NitroNullableBool {
    return NitroNullableBool(
      hasValue: r.readBool(),
      value: r.readBool(),
    )
  }

  public func writeFields(_ writer: NitroRecordWriter) {
    writer.writeBool(hasValue)
    writer.writeBool(value)
  }

  public func toNative() -> UnsafeMutablePointer<UInt8>? {
    let writer = NitroRecordWriter()
    writeFields(writer)
    return writer.toNative()
  }
}

public class NitroRecordWriter {
    public var bytes: [UInt8] = []
    public init() {}
    public func writeInt(_ v: Int64) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeInt32(_ v: Int32) {
        var val = v.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeDouble(_ v: Double) {
        var val = v.bitPattern.littleEndian
        withUnsafeBytes(of: &val) { bytes.append(contentsOf: $0) }
    }
    public func writeBool(_ v: Bool) {
        bytes.append(v ? 1 : 0)
    }
    public func writeString(_ v: String) {
        let utf8 = Array(v.utf8)
        writeInt32(Int32(utf8.count))
        bytes.append(contentsOf: utf8)
    }
    public func writeNullTag(_ isNull: Bool) {
        bytes.append(isNull ? 0 : 1)
    }
    public func writeBlob(_ v: Data) {
        writeInt32(Int32(v.count))
        bytes.append(contentsOf: Array(v))
    }
    public func toNative() -> UnsafeMutablePointer<UInt8>? {
        let total = 4 + bytes.count
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: total)
        var length = Int32(bytes.count).littleEndian
        _ = memcpy(ptr, &length, 4)
        if bytes.count > 0 {
            _ = memcpy(ptr.advanced(by: 4), bytes, bytes.count)
        }
        return ptr
    }
    public static func encodeList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        let w = NitroRecordWriter()
        w.writeInt32(Int32(items.count))
        for item in items { writeItem(w, item) }
        return w.toNative()
    }
    /// Encodes a list with a per-item byte-offset table for O(1) random access.
    /// Wire format (payload after outer 4B length prefix):
    ///   [int32 count][int64 × count offsets from payload start][item bytes...]
    /// Counterpart: Dart LazyRecordList.decode / RecordWriter.encodeIndexedList.
    public static func encodeIndexedList<T>(_ items: [T], writeItem: (NitroRecordWriter, T) -> Void) -> UnsafeMutablePointer<UInt8>? {
        var blobs: [[UInt8]] = []
        for item in items {
            let w = NitroRecordWriter()
            writeItem(w, item)
            blobs.append(w.bytes)
        }
        var pos = 4 + 8 * blobs.count
        var offsets: [Int64] = []
        for blob in blobs {
            offsets.append(Int64(pos))
            pos += blob.count
        }
        let w = NitroRecordWriter()
        w.writeInt32(Int32(blobs.count))
        for off in offsets { w.writeInt(off) }
        for blob in blobs { w.bytes.append(contentsOf: blob) }
        return w.toNative()
    }
}

public class NitroRecordReader {
    public let bytes: UnsafeMutablePointer<UInt8>
    public var pos: Int = 0
    public init(ptr: UnsafeMutablePointer<UInt8>) {
        self.bytes = ptr.advanced(by: 4)
    }
    public init(payload: UnsafeMutablePointer<UInt8>) {
        self.bytes = payload
    }
    public func readInt() -> Int64 {
        var v: Int64 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 8)
        pos += 8
        return Int64(littleEndian: v)
    }
    public func readInt32() -> Int32 {
        var v: Int32 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 4)
        pos += 4
        return Int32(littleEndian: v)
    }
    public func readDouble() -> Double {
        var v: UInt64 = 0
        _ = memcpy(&v, bytes.advanced(by: pos), 8)
        pos += 8
        return Double(bitPattern: UInt64(littleEndian: v))
    }
    public func readBool() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v != 0
    }
    public func readString() -> String {
        let len = Int(readInt32())
        guard len > 0 else { return "" }
        let s = String(bytes: UnsafeBufferPointer(start: bytes.advanced(by: pos), count: len), encoding: .utf8) ?? ""
        pos += len
        return s
    }
    public func readNullTag() -> Bool {
        let v = bytes[pos]
        pos += 1
        return v == 0
    }
    public func readBlob() -> Data {
        let len = Int(readInt32())
        let data = Data(bytes: bytes.advanced(by: pos), count: len)
        pos += len
        return data
    }
    public func readBlobAsPointer() -> UnsafeMutablePointer<UInt8>? {
        let len = Int(readInt32())
        if (len == 0) { return nil }
        let ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: len)
        ptr.initialize(from: bytes.advanced(by: pos), count: len)
        pos += len
        return ptr
    }
    public static func decodeList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
    /// Decodes a list encoded by Dart's RecordWriter.encodeIndexedList / encodeIndexedPrimitiveList.
    /// Wire format (payload after outer 4B length prefix):
    ///   [int32 count][int64 × count offsets from payload start][item bytes...]
    /// The offset table is skipped; items are read sequentially after it.
    public static func decodeIndexedList<T>(_ ptr: UnsafeMutablePointer<UInt8>, readItem: (NitroRecordReader) -> T) -> [T] {
        let r = NitroRecordReader(ptr: ptr)
        let count = r.readInt32()
        r.pos += Int(count) * 8  // skip Int64 offset table
        var items: [T] = []
        for _ in 0..<count {
            items.append(readItem(r))
        }
        return items
    }
}

/**
 * Protocol for the NitroTorch module.
 * Conform to this in your Swift source code.
 * Nitro may call this implementation from any native thread.
 * Keep mutable state thread-safe or marshal work onto your own queue/actor.
 */
public protocol HybridNitroTorchProtocol: AnyObject {
    // source: nitro_torch.native.dart:17
    func onCallback(callback: @escaping (TorchState) -> Void) -> Void
    // source: nitro_torch.native.dart:20
    func turnOn() -> Void
    // source: nitro_torch.native.dart:23
    func turnOff() -> Void
    // source: nitro_torch.native.dart:26
    func getStatus() -> Bool
    // source: nitro_torch.native.dart:29
    func toggle() -> Void
    // source: nitro_torch.native.dart:32
    func setLevel(level: Int64) -> Void
    // source: nitro_torch.native.dart:43
    func maxLevel() -> Int64?
    var onLevelChanged: AnyPublisher<TorchLevel, Never> { get }
    var onTorchStateChanged: AnyPublisher<TorchState, Never> { get }
}

public class NitroTorchRegistry {
    public static var impl: HybridNitroTorchProtocol?

    public static func register(_ impl: HybridNitroTorchProtocol) {
        NitroTorchRegistry.impl = impl
    }

    // Stream: onLevelChanged cancellables keyed by dartPort
    public static var _onLevelChangedCancellables = [Int64: AnyCancellable]()

    // Stream: onTorchStateChanged cancellables keyed by dartPort
    public static var _onTorchStateChangedCancellables = [Int64: AnyCancellable]()
}

// MARK: - C bridge stubs — exported as C symbols called by the generated .cpp shim

// source: nitro_torch.native.dart:17
@_cdecl("_nitro_torch_call_onCallback")
public func _nitro_torch_call_onCallback(_ callback: @convention(c) (Int64) -> Void) -> Void {
    NitroTorchRegistry.impl?.onCallback(callback: { arg0 in callback(arg0.rawValue) })
}

// source: nitro_torch.native.dart:20
@_cdecl("_nitro_torch_call_turnOn")
public func _nitro_torch_call_turnOn() -> Void {
    NitroTorchRegistry.impl?.turnOn()
}

// source: nitro_torch.native.dart:23
@_cdecl("_nitro_torch_call_turnOff")
public func _nitro_torch_call_turnOff() -> Void {
    NitroTorchRegistry.impl?.turnOff()
}

// source: nitro_torch.native.dart:26
@_cdecl("_nitro_torch_call_getStatus")
public func _nitro_torch_call_getStatus() -> Int8 {
    return Int8((NitroTorchRegistry.impl?.getStatus() ?? false) ? 1 : 0)
}

// source: nitro_torch.native.dart:29
@_cdecl("_nitro_torch_call_toggle")
public func _nitro_torch_call_toggle() -> Void {
    NitroTorchRegistry.impl?.toggle()
}

// source: nitro_torch.native.dart:32
@_cdecl("_nitro_torch_call_setLevel")
public func _nitro_torch_call_setLevel(_ level: Int64) -> Void {
    NitroTorchRegistry.impl?.setLevel(level: level)
}

// source: nitro_torch.native.dart:43
@_cdecl("_nitro_torch_call_maxLevel")
public func _nitro_torch_call_maxLevel() -> Int64 {
    guard let impl = NitroTorchRegistry.impl else { return Int64.min }
    return impl.maxLevel() ?? Int64.min
}

@_cdecl("_nitro_torch_register_onLevelChanged_stream")
public func _nitro_torch_register_onLevelChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, UnsafeMutableRawPointer?) -> Bool
) {
    NitroTorchRegistry._onLevelChangedCancellables[dartPort] =
        NitroTorchRegistry.impl?.onLevelChanged.sink { item in
            let ptr = UnsafeMutablePointer<_TorchLevelC>.allocate(capacity: 1)
            ptr.initialize(to: _TorchLevelC.fromSwift(item))
            if !emitCb(dartPort, UnsafeMutableRawPointer(ptr)) {
                ptr.deinitialize(count: 1)
                ptr.deallocate()
                NitroTorchRegistry._onLevelChangedCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_torch_release_onLevelChanged_stream")
public func _nitro_torch_release_onLevelChanged_stream(_ dartPort: Int64) {
    NitroTorchRegistry._onLevelChangedCancellables[dartPort]?.cancel()
    NitroTorchRegistry._onLevelChangedCancellables.removeValue(forKey: dartPort)
}
@_cdecl("_nitro_torch_register_onTorchStateChanged_stream")
public func _nitro_torch_register_onTorchStateChanged_stream(
    _ dartPort: Int64,
    _ emitCb: @convention(c) (Int64, Int64) -> Bool
) {
    NitroTorchRegistry._onTorchStateChangedCancellables[dartPort] =
        NitroTorchRegistry.impl?.onTorchStateChanged.sink { item in
            if !emitCb(dartPort, item.rawValue) {
                NitroTorchRegistry._onTorchStateChangedCancellables.removeValue(forKey: dartPort)?.cancel()
            }
        }
}

@_cdecl("_nitro_torch_release_onTorchStateChanged_stream")
public func _nitro_torch_release_onTorchStateChanged_stream(_ dartPort: Int64) {
    NitroTorchRegistry._onTorchStateChangedCancellables[dartPort]?.cancel()
    NitroTorchRegistry._onTorchStateChangedCancellables.removeValue(forKey: dartPort)
}
