// Generated by Nitrogen Modules. Do not edit.
// Generated from: nitro_torch.native.dart
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#ifndef NITRO_EXPORT
#  if defined(_WIN32)
#    define NITRO_EXPORT __declspec(dllexport)
#  else
#    define NITRO_EXPORT __attribute__((visibility("default"))) __attribute__((used))
#  endif
#endif

#ifndef NITRO_ERROR_DEFINED
#define NITRO_ERROR_DEFINED
typedef struct {
  int8_t hasError;
  const char* name;
  const char* message;
  const char* code;
  const char* stackTrace;
} NitroError;
#endif

#ifdef __cplusplus
extern "C" {
#endif

NITRO_EXPORT intptr_t nitro_torch_init_dart_api_dl(void* data);
NITRO_EXPORT NitroError* nitro_torch_get_error(void);
NITRO_EXPORT void nitro_torch_clear_error(void);



// Methods
NITRO_EXPORT double nitro_torch_add(double a, double b);
NITRO_EXPORT const char* nitro_torch_get_greeting(const char* name);

#ifdef __cplusplus
}
#endif
